### ISSUE TITLE
Use pygments classes instead of inline css

### ISSUE THREAD

**Issue by badlydrawnrob** [Neftas/supplementary-buttons-anki#87]
So [digging into your code](https://github.com/Neftas/supplementary-buttons-anki/search?utf8=%E2%9C%93&q=noclasses), it seems like you've modified the [Code highlighting](https://github.com/waylan/Python-Markdown/blob/master/markdown/extensions/codehilite.py) plugin to [output inline styles](https://github.com/Neftas/supplementary-buttons-anki/issues/55#issuecomment-253556975), rather than using the [default Pygments css classes](http://pygments.org/docs/quickstart/#example). E.g:

```
<span style="color: #204a87; font-weight: bold">while</span>
```

instead of ...

```
<span class="k">while</span>
```

Personally, I think this is bad practice as it makes it difficult (or impossible) to modify the theme manually (or locks us into this plugin).

I'd like to see an option to use Pygments as it was intended, as unless I'm missing something this isn't possible right now. I'm not a good enough Python developer to modify the plugin to do this myself either!

It's a shame, as it's an otherwise great feature.

**Comment by badlydrawnrob** [comment]
Commenting out this section of [this file](https://github.com/Neftas/supplementary-buttons-anki/blob/7cc89bfef12f03461f0ba74f14dd525c22779ee0/extra_buttons/utility.py) seems to do the job, for now.

```python
CodeHiliteExtension(
                noclasses=True,
                pygments_style=preferences.PREFS.get(const.MARKDOWN_SYNTAX_STYLE),
linenums=preferences.PREFS.get(const.MARKDOWN_LINE_NUMS)),
```

Now outputs:

```html
<div class=""codehilite"" align=""left""><pre><span class=""o"">&gt;&gt;&gt;</span> <span class=""n"">word</span> <span class=""o"">=</span> <span class=""s"">'Spam!'</span> <span class=""o"">&gt;&gt;&gt;</span> <span class=""n"">publish</span><span class=""p"">(</span><span class=""n"">word</span><span class=""p"">)</span> </pre></div>
```

The `align="left"` is still there, which ideally I'd like disabled also.

**Comment by Neftas** [comment]
@badlydrawnrob Haha, I'm not quite as evil as you would have me ;-)

I am using the API of Python-Markdown to create blocks of code with inline styling. I did this on purpose, so as to not force everyone to read the Pygments documentation and write tens of lines of CSS before being able to use this add-on. You might be surprised, but not everyone knows CSS or is inclined to write their own style sheets. I also put around 20 different styles in a drop-down menu in the options, so everyone would be able to quickly choose a theme that they like. (Also, a knowing person can easily create their own Pygments style or download one, and add it to this add-on by dropping it in the correct folder.)

> Personally, I think this is bad practice

It would be, if I were designing a website. As it stands, you are the first one who explicitly wants to define his own style sheet. Other people just want this to work out of the box.

But I can see how defining your own style sheet would be helpful. How about I create an option that allows you to switch between inline styling and style sheets? I will also remove the `align="left"` in that case, so you are unhindered in defining your style. Would that work for you? :)

(Sorry, but this line made me laugh:

> it makes it difficult (or impossible) to modify the theme manually (or locks us into this plugin)

Yes, it's has been my plan from the beginning to lock people into my OPEN-SOURCE plugin ;-)

**Comment by badlydrawnrob** [comment]
@Neftas Haha. First of all, if I came across as an arrogant ass, that wasn't my intention. I've had a [frustrating time trying to get a workable highlighting solution](https://github.com/badlydrawnrob/anki/issues/21) and really, you're doing an amazing job with this plugin. It's really speeding up my workflow.

I can understand the thinking behind inline styles, but as Anki spews out pretty ugly code I had high hopes for Power Format Pack; it feels so much nicer writing Markdown and even better if it converts to decent HTML for styling. As you say, the Pygments documentation is a bit of a beast so would put a lot of users off. I guess I figured this plugin was aimed at developers with your Markdown/Code blocks implementation.

> it makes it difficult (or impossible) to modify the theme manually (or locks us into this plugin)

I didn't mean that you're some evil plugin developer out to dominate the Anki market! I just meant that some form of flexibility is more preferable in my case. I guess `!important` markup could be used, but css classes seem far cleaner to me — so what you've suggested would be great.

I've actually only just updated your plugin, preferences are making a lot more sense now.

**Comment by badlydrawnrob** [comment]
So to summise, a big **yes!** for `noclasses=True` and `noclasses=False` preferences. Also, just to be pedantic, should there be a `<code>` tag within `<pre>`?

**Comment by Neftas** [comment]
Alright, I will look into this. (I already made it easier for tables to be styled using style sheets instead of using inline styling (that would be the "table button", not the Markdown table)).

As for specific tags that get generated (`<code>` elements within `<pre>`): that is all Python-Markdown, I simply call their API and they generate the code.

**Comment by Neftas** [comment]
@badlydrawnrob I have just pulled a change to branch develop in b8fea08. Can you tell me if this is what you wanted? I would appreciate your feedback before pushing it to master and publishing it on AnkiWeb.

**Comment by badlydrawnrob** [comment]
@Neftas Hey, just saw your message. Yeah, that looks exactly what I was after thanks! You've gotten rid of the `pre` align too, which is great :)

Just one point though, did you remove the `<div class="codehilite">` section from the rendered code?

<img width="763" alt="screen shot 2016-11-19 at 18 18 39" src="https://cloud.githubusercontent.com/assets/1176875/20457568/1061cd30-ae86-11e6-8e8f-d79361567e66.png">


I think, for safety, you should have a similar to your **general** options, where we could select a class to slot into the `<pre>` or `<code>` tag, similar to [highlight.js](https://highlightjs.org/usage/)

<img width="418" alt="screen shot 2016-11-19 at 18 26 37" src="https://cloud.githubusercontent.com/assets/1176875/20457559/faaad09a-ae85-11e6-86ca-d760f8b6687d.png">

 My current CSS is as below:

<img width="643" alt="screen shot 2016-11-19 at 18 23 50" src="https://cloud.githubusercontent.com/assets/1176875/20457561/0074e4de-ae86-11e6-97fe-f65c279fce4d.png">

Other than that, seems to be working great!

**Comment by Neftas** [comment]
Hi @badlydrawnrob, sorry for a (very) late reply. When I switch to Markdown, I still get the `<div class="codehilite">`. Are you sure it is gone?

Since that class serves as an indicator that what is coming next is a pygments code-highlighted section, I think adding another class would be redundant, don't you think so?

**Comment by badlydrawnrob** [comment]
@Neftas Hey Stefan, so it does in fact seem to be adding the `codehilite` class when converting to Markdown, when you copy and paste the converted Markdown into another field, however, it seems to strip the `div` wrapper. You're adding it with js? I guess this was the issue I was seeing, probably a brain fart on my part ;)

Either way, this solves my needs just fine, so as you say, no need for another class so long as this one remains. And no worries with the reply time, I know what it's like! 👍

**Comment by byronaltice** [comment]
I'm having some difficulty figuring out the css I need to be able to use a custom stylesheet here. 
How do I see which classes I need to style?

Will my custom css be added to code blocks in this format?
```
```javascript
console.log('hey')
```
```

**Comment by byronaltice** [comment]
I think I figured it out? If you have a comment in the CSS style, anything after the comment does not apply, unless you put a {} at the end of the comment: 

`
// Power format pack {} 

.front .codehilite .nx { color: red; }
.back .codehilite .nx { color: red; }
`
the {} in the comment is required, the styling will not work without it

Is this intentional?

**Comment by byronaltice** [comment]
I'm having some trouble figuring out how to apply custom styles... 

The pygments documentation doesn't really say what classes apply to which elements.

I've figured out that .nx is keywords, and .c is comments, and .p is punctuation, but beyond that I'm not sure.

Do you have a map of the css classes to the code elements? Or am I missing something in the pygments documentation?

Thanks for all your wonderful work.

**Comment by Neftas** [comment]
This is what I found with a DuckDuckGo search:

```css
.highlight .hll { background-color: #d6d6d6 }
.highlight  { background: #ffffff; color: #4d4d4c }
.highlight .c { color: #8e908c } /* Comment */
.highlight .err { color: #c82829 } /* Error */
.highlight .k { color: #8959a8 } /* Keyword */
.highlight .l { color: #f5871f } /* Literal */
.highlight .n { color: #4d4d4c } /* Name */
.highlight .o { color: #3e999f } /* Operator */
.highlight .p { color: #4d4d4c } /* Punctuation */
.highlight .cm { color: #8e908c } /* Comment.Multiline */
.highlight .cp { color: #8e908c } /* Comment.Preproc */
.highlight .c1 { color: #8e908c } /* Comment.Single */
.highlight .cs { color: #8e908c } /* Comment.Special */
.highlight .gd { color: #c82829 } /* Generic.Deleted */
.highlight .ge { font-style: italic } /* Generic.Emph */
.highlight .gh { color: #4d4d4c; font-weight: bold } /* Generic.Heading */
.highlight .gi { color: #718c00 } /* Generic.Inserted */
.highlight .gp { color: #8e908c; font-weight: bold } /* Generic.Prompt */
.highlight .gs { font-weight: bold } /* Generic.Strong */
.highlight .gu { color: #3e999f; font-weight: bold } /* Generic.Subheading */
.highlight .kc { color: #8959a8 } /* Keyword.Constant */
.highlight .kd { color: #8959a8 } /* Keyword.Declaration */
.highlight .kn { color: #3e999f } /* Keyword.Namespace */
.highlight .kp { color: #8959a8 } /* Keyword.Pseudo */
.highlight .kr { color: #8959a8 } /* Keyword.Reserved */
.highlight .kt { color: #eab700 } /* Keyword.Type */
.highlight .ld { color: #718c00 } /* Literal.Date */
.highlight .m { color: #f5871f } /* Literal.Number */
.highlight .s { color: #718c00 } /* Literal.String */
.highlight .na { color: #4271ae } /* Name.Attribute */
.highlight .nb { color: #4d4d4c } /* Name.Builtin */
.highlight .nc { color: #eab700 } /* Name.Class */
.highlight .no { color: #c82829 } /* Name.Constant */
.highlight .nd { color: #3e999f } /* Name.Decorator */
.highlight .ni { color: #4d4d4c } /* Name.Entity */
.highlight .ne { color: #c82829 } /* Name.Exception */
.highlight .nf { color: #4271ae } /* Name.Function */
.highlight .nl { color: #4d4d4c } /* Name.Label */
.highlight .nn { color: #eab700 } /* Name.Namespace */
.highlight .nx { color: #4271ae } /* Name.Other */
.highlight .py { color: #4d4d4c } /* Name.Property */
.highlight .nt { color: #3e999f } /* Name.Tag */
.highlight .nv { color: #c82829 } /* Name.Variable */
.highlight .ow { color: #3e999f } /* Operator.Word */
.highlight .w { color: #4d4d4c } /* Text.Whitespace */
.highlight .mf { color: #f5871f } /* Literal.Number.Float */
.highlight .mh { color: #f5871f } /* Literal.Number.Hex */
.highlight .mi { color: #f5871f } /* Literal.Number.Integer */
.highlight .mo { color: #f5871f } /* Literal.Number.Oct */
.highlight .sb { color: #718c00 } /* Literal.String.Backtick */
.highlight .sc { color: #4d4d4c } /* Literal.String.Char */
.highlight .sd { color: #8e908c } /* Literal.String.Doc */
.highlight .s2 { color: #718c00 } /* Literal.String.Double */
.highlight .se { color: #f5871f } /* Literal.String.Escape */
.highlight .sh { color: #718c00 } /* Literal.String.Heredoc */
.highlight .si { color: #f5871f } /* Literal.String.Interpol */
.highlight .sx { color: #718c00 } /* Literal.String.Other */
.highlight .sr { color: #718c00 } /* Literal.String.Regex */
.highlight .s1 { color: #718c00 } /* Literal.String.Single */
.highlight .ss { color: #718c00 } /* Literal.String.Symbol */
.highlight .bp { color: #4d4d4c } /* Name.Builtin.Pseudo */
.highlight .vc { color: #c82829 } /* Name.Variable.Class */
.highlight .vg { color: #c82829 } /* Name.Variable.Global */
.highlight .vi { color: #c82829 } /* Name.Variable.Instance */
.highlight .il { color: #f5871f } /* Literal.Number.Integer.Long */
```

But please, open a new ticket for your issues, instead of commenting on closed ones.
